var ALL_WORKFLOWS = [
{u:'https://www.growwstacks.com/workflows/scrape-tiktok-trends-and-generate-ai-videos-with-apify-fal-ai-and-google-suite',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/11003-scrape-tiktok-trends-and-generate-ai-videos-with-apify.png',t:'Scrape Tiktok Trends And Generate AI Videos With Apify Fal AI And Google Suite'},
{u:'https://www.growwstacks.com/workflows/generate-podcast-transcript-summaries-and-keywords-with-openai-and-gmail',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/6661-generate-podcast-transcript-summaries-and-keywords-with.png',t:'Generate Podcast Transcript Summaries And Keywords With Openai And Gmail'},
{u:'https://www.growwstacks.com/workflows/monitor-competitor-meta-ads-creatives-and-send-alerts-with-google-sheets-and-telegram',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/11270-monitor-competitor-meta-ads-creatives-and-send-alerts-.png',t:'Monitor Competitor Meta Ads Creatives And Send Alerts With Google Sheets And Telegram'},
{u:'https://www.growwstacks.com/workflows/gemini-powered-facebook-comment-and-dm-assistant-with-notion',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/8066-gemini-powered-facebook-comment-and-dm-assistant-with-n.png',t:'Gemini Powered Facebook Comment And Dm Assistant With Notion'},
{u:'https://www.growwstacks.com/workflows/create-update-and-get-an-issue-on-taiga',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/685-create-update-and-get-an-issue-on-taiga.png',t:'Create Update And Get An Issue On Taiga'},
{u:'https://www.growwstacks.com/workflows/automate-lead-intake-and-crm-with-tally-forms-to-google-sheets-and-sendgrid-emails',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/11233-automate-lead-intake-and-crm-with-tally-forms-to-googl.png',t:'Automate Lead Intake And Crm With Tally Forms To Google Sheets And Sendgrid Emails'},
{u:'https://www.growwstacks.com/workflows/linkedin-company-icp-scoring-automation-with-airtop-and-google-sheets',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/3475-linkedin-company-icp-scoring-automation-with-airtop-and.png',t:'Linkedin Company Icp Scoring Automation With AIrtop And Google Sheets'},
{u:'https://www.growwstacks.com/workflows/automate-real-estate-property-tours-with-google-calendar-slack-and-calendly',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/6377-automate-real-estate-property-tours-with-google-calenda.png',t:'Automate Real Estate Property Tours With Google Calendar Slack And Calendly'},
{u:'https://www.growwstacks.com/workflows/meta-ads-to-google-sheets-daily-and-historical-campaign-performance-report',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/11499-meta-ads-to-google-sheets-daily-and-historical-campaig.png',t:'Meta Ads To Google Sheets Daily And Historical Campaign Performance Report'},
{u:'https://www.growwstacks.com/workflows/send-automated-daily-reminders-on-telegram',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/1387-send-automated-daily-reminders-on-telegram.png',t:'Send Automated Daily Reminders On Telegram'},
{u:'https://www.growwstacks.com/workflows/build-a-full-rest-api-with-n8n-webhooks',i:'https://ik.imagekit.io/r2zdlyze2o/GS-Website/N8N-Workflows/12789-build-a-full-rest-api-with-n8n-webhooks.png',t:'Build A Full Rest Api With N8N Webhooks'},
];